# Generated by Django 3.2.18 on 2023-05-16 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_dttm', models.DateTimeField()),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.member')),
            ],
            options={
                'db_table': 'QUESTION',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_dttm', models.DateTimeField()),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.question')),
            ],
            options={
                'db_table': 'ANSWER',
            },
        ),
    ]
