# Generated by Django 3.2.18 on 2023-05-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='writerID',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
