# Generated by Django 3.2.18 on 2023-04-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberID', models.CharField(max_length=15, verbose_name='아이디')),
                ('password', models.CharField(max_length=15, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=30, verbose_name='사용자명')),
                ('email', models.EmailField(max_length=30, verbose_name='이메일')),
                ('register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='회원가입일자')),
            ],
            options={
                'db_table': 'MEMBER',
            },
        ),
    ]
